name: mitiq-dev
channels:
  - conda-forge
dependencies:
# Third-party integration.
  - pyquil~=3.1.0
  - pennylane~=0.21.0
  - amazon-braket-sdk~=1.14.0
# Unit tests, coverage, and formatting/style.
  - pytest-xdist[psutil]~=2.5.0
  - pytest-cov~=3.0.0
  - flake8~=4.0.1
  - black~=22.1
  - mypy~=0.931
# Documentation and examples.
  - sphinxcontrib-bibtex~=2.4.1
  - sphinx-copybutton~=0.5.0
  - sphinx-autodoc-typehints~=1.17.0
  - myst-nb~=0.13.2
  - pydata-sphinx-theme~=0.8.0
  - jupytext~=1.13.7
  - sphinx-gallery~=0.10.1
  - nbsphinx~=0.8.8
  - pip
  - pip:
    - qiskit~=0.32.1
    - pennylane-qiskit~=0.21.0
# variables:
#   VAR1: valueA
#   VAR2: valueB